### ISSUE TITLE
Add re-stream proxy support

### ISSUE THREAD

**Issue by barlowd55** [asabino2/streamproxy#2]
Is there a possibility to restream support to multiple clients so that only 1 ffmpeg process is spawn for 1 channel and connects to n users.

**Comment by asabino2** [comment]
i will check this possibility

**Comment by asabino2** [comment]
New feature in version 1.1.1: http://localhost:3000/streamserver/create?url=https://cdnlive.shooowit.net/canalextremaduralive/smil:channel1DVR.smil/playlist.m3u8&port=4212

for more information, see readme.md
