### ISSUE TITLE
unable to Open Web Interface On Ubuntu 

### ISSUE THREAD

**Issue by Restreamdev** [asabino2/streamproxy#3]
hello dev

its a nice tool
i have installed on winodws 10 using docker its working fine but same issue its not opening on port 4211 but
i have some issue with it
i have installed Streamproxy using docker on ubuntu server
i cant open web interface as mention on serverip:port

i m very thankful if you add some guide on github and on dockerhub

**Comment by asabino2** [comment]
hi Restreamdev,

first, thanks for feedback and message.

Can you describe the error you are experiencing?
if possible send a step-by-step for the error simulation
Remembering that to use docker you need to map port 4211 to your host port

execution example

docker run -d --rm -p 4211:4211 asabino2/streamproxy

now just go to a web browser and call http://localhost:4211, there you will see a mini tutorial on how to use the tool

I'm working on improvements, which will be released soon, including the persistence of streamservers

another question: it is necessary to have ffmpeg and streamlink installed on the computer (in case it is used on linux without using docker)

Att.

**Comment by Restreamdev** [comment]
Thanks You Very Much Sir 
its Working Now 
im eagerly Wiating For 
Your Next Update
