### ISSUE TITLE
Possible to create Stream Server On Demand

### ISSUE THREAD

**Issue by barlowd55** [asabino2/streamproxy#4]
Is it possible to create Stream server on demand? 

That is the stream server should only be active once a client connects, continue streaming for all other clients and then destroy, once all clients are disconnected for a specific stream server. 

This helps to save upstream bandwidth and manage open connections on the source.

**Comment by asabino2** [comment]
feature released in version 1.3.7

**Comment by barlowd55** [comment]
I have just tried this new version. I am trying to create a new stream server using the link:

http://localhost:3000/videostream/ffmpeg?url=https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8&streamserver=red

it gives the following error.

```
opening connect to stream in url  https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8 from ::ffff:104.28.232.91
Caught exception: TypeError: Cannot set property 'status' of undefined
Exception origin: uncaughtException
```

**Comment by asabino2** [comment]
Hi Barlowd55,

actually creating a streamserver via a direct url has a bug (however this
way of creating a streamserver is deprecated), instead use the wizard to
create streamservers, just access the url
http://localhost:3000/streamserver/create

you can see the list of created stream servers and even create a new one,
edit or delete via url http://localhost:3000/streamserver/list

Att.

Em dom., 2 de abr. de 2023 às 04:20, barlowd55 ***@***.***>
escreveu:
